### ISSUE TITLE
MemoryNet训练时候一些问题

### ISSUE THREAD

**Issue by qdd1234** [SegmentationBLWX/sssegmentation#13]
您好，我使用您的MemoryNet进行医学图像分割，当和OCRNet训练相同轮数的时候，MemoryNet的miou比OCRNet低很多，这是什么原因

**Comment by CharlesPikachu** [comment]
不清楚你的setting和dataset，我目前主要做的自然图像，但是据我所知，fcn的head在某些医学数据集上的表现也是优于psp，aspp和ocr这些head的。
