### ISSUE TITLE
What does the 'fine-tuned' mean?

### ISSUE THREAD

**Issue by liuzhidemaomao** [SegmentationBLWX/sssegmentation#14]
In ISNet, the models are fine-tuned for 160K iterations on ADE20K and LIP datasets. So do you pretrained the models on other datasets?

**Comment by CharlesPikachu** [comment]
It means that the backbone networks are pretrained on ImageNet 1k/22k, which is a common practice in semantic segmentation.

**Comment by liuzhidemaomao** [comment]
> It means that the backbone networks are pretrained on ImageNet 1k/22k, which is a common practice in semantic segmentation.

Thank you for your reply.
