### ISSUE TITLE
Is there should be 'continue'? 

### ISSUE THREAD

**Issue by EricKani** [SegmentationBLWX/sssegmentation#16]
https://github.com/SegmentationBLWX/sssegmentation/blob/7a405b1a4949606deae067223ebd68cceec6b225/ssseg/modules/models/memorynet/memory.py#L176

If there are more than one 'num_feats_per_cls' in the furture, 'break' will make this for loop only update the first memory_feature?

**Comment by CharlesPikachu** [comment]
if num_feats_per_cls > 1, the representations of the same category  in memory bank should be different.
