### ISSUE TITLE
how to train with multi-gpu in one machine

### ISSUE THREAD

**Issue by Kenneth-X** [SegmentationBLWX/sssegmentation#17]
hi，i wanna train the model with 4 gpus in one machine
however, your code 'distrain.sh' and 'train.py'  can only  train with distributed mode in multi-machine
how can i modify the code ?

**Comment by CharlesPikachu** [comment]
any error info? In fact, distributed mode in pytorch also support training the model with multi-gpus in one machine

**Comment by Kenneth-X** [comment]
code can run with no bug  ,but  only 4gpus can be used(i got 8 gpus)
my distrain.py is follow：
#!/bin/bash
THIS_DIR="$( cd "$( dirname "$0" )" && pwd )"
cd $THIS_DIR
cd ..
NGPUS=8
CFGFILEPATH="/home/xt.xie/workspace/code/sssegmentation-main/ssseg/cfgs/deeplabv3plus/cfgs_apollo_resnet50os8.py"
CHECKPOINTSPATH="/home/xt.xie/workspace/code/sssegmentation-main/model/deeplabv3plus_resnet50os8_cityscapes_train.pth"
PORT=${PORT:-8888}
python3 -m torch.distributed.launch --nproc_per_node $NGPUS \
--master_port $PORT ssseg/train.py --nproc_per_node $NGPUS --cfgfilepath $CFGFILEPATH --checkpointspath $CHECKPOINTSPATH



Fri Nov 19 04:05:51 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      On   | 00000000:0E:00.0 Off |                    0 |
| N/A   52C    P0   326W / 400W |  19652MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A100-SXM4-40GB      On   | 00000000:13:00.0 Off |                    0 |
| N/A   51C    P0   321W / 400W |  19736MiB / 40536MiB |     97%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  A100-SXM4-40GB      On   | 00000000:4A:00.0 Off |                    0 |
| N/A   51C    P0   295W / 400W |  19748MiB / 40536MiB |     95%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  A100-SXM4-40GB      On   | 00000000:50:00.0 Off |                    0 |
| N/A   55C    P0   327W / 400W |  19664MiB / 40536MiB |     98%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  A100-SXM4-40GB      On   | 00000000:93:00.0 Off |                    0 |
| N/A   30C    P0    58W / 400W |      3MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  A100-SXM4-40GB      On   | 00000000:99:00.0 Off |                    0 |
| N/A   27C    P0    53W / 400W |      3MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  A100-SXM4-40GB      On   | 00000000:CB:00.0 Off |                    0 |
| N/A   27C    P0    51W / 400W |      3MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  A100-SXM4-40GB      On   | 00000000:D0:00.0 Off |                    0 |
| N/A   28C    P0    53W / 400W |      3MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by CharlesPikachu** [comment]
I guess the reason is the batch size is only four?
