### ISSUE TITLE
单机多卡问题

### ISSUE THREAD

**Issue by phk1042791021** [SegmentationBLWX/sssegmentation#19]
你好，请教一下单机多卡问题，
不管设置gpu数量为多少，实际只使用了一张卡
默认的bs=8，单卡显存可以吃满，改为16还是一张卡，也没有溢出
无任何报错

**Comment by CharlesPikachu** [comment]
可以把你的命令和对应的config贴一下么

**Comment by phk1042791021** [comment]
config直接使用icnet原版没有动过https://github.com/SegmentationBLWX/sssegmentation/blob/main/ssseg/cfgs/icnet/cfgs_cityscapes_resnet50os8.py，
启动命令python -m torch.distributed.launch train.py
其他启动参数都是直接修改train.py   parseArgs中的默认值


另外想请教一下icnet中使用resnet50，bs=8 达到了76.6，请问这个结果是单卡为bs=8还是整体为8训练出来的呢

**Comment by CharlesPikachu** [comment]
使用方式请参考：https://sssegmentation.readthedocs.io/en/latest/QUICKSTART.html
config中的bs都是整体的bs，你用scripts里的脚本启动，比如：
`sh scripts/distrain.sh ${NGPUS} ${CFGFILEPATH}`

**Comment by phk1042791021** [comment]
感谢大佬，是我瞎改改出问题了
