### ISSUE TITLE
how to train other datasets

### ISSUE THREAD

**Issue by ASguoyue** [SegmentationBLWX/sssegmentation#20]
train the datasets by mask and imgs .  how to finish it

**Comment by CharlesPikachu** [comment]
First you need to add the py file (e.g., yourdatasetname.py) in ./ssseg/modules/datasets according to your dataset format, and then add it in the corresponding builder.py.

You can refer to ./ssseg/modules/datasets/ade20k.py to write your own dataset class.

**Comment by shituo123456** [comment]
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

how to deal with it
