### ISSUE TITLE
segformer里输出通道似乎不对，原[64,128,320,512], 本[64,128,256,512]?

### ISSUE THREAD

**Issue by swjtulinxi** [SegmentationBLWX/sssegmentation#21]

**Comment by CharlesPikachu** [comment]
backbone有不同的setting，请仔细阅读论文。

**Comment by swjtulinxi** [comment]
![image](https://user-images.githubusercontent.com/50089266/148479314-b509db5d-da00-4d76-983e-41651bb08f6f.png)
我只看到这个啊，请问另一个设置也是在segformer论文里吗
