### ISSUE TITLE
SWIN-B with DeepLabv3+ training on custom dataset

### ISSUE THREAD

**Issue by deshwalmahesh** [SegmentationBLWX/sssegmentation#23]
Hi, I am learning about Segmentation and want to try out the segmentation my custom data set. Could you please provide steps on how to use supported backbones with some particular architectures?

If I want to use `SWIN-B` as my backbone on `DeepLabV3+` using a custom dataset, what should be the commands and all. I could not find anything on the docs and on the github page. Could you please help.

**Comment by CharlesPikachu** [comment]
you can create a new config under the "deeplabv3plus" directory and set the SEGMENTOR_CFG to call SWIN-B
