### ISSUE TITLE
MemoryNetV2 相关问题

### ISSUE THREAD

**Issue by jyang68sh** [SegmentationBLWX/sssegmentation#27]
非常精彩的论文，

有个问题，根据我的代码阅读，MemoryNetV2在推理的时候也会过self-attention block

是不是考虑在推理的时候换一种attention模块去做历史特征的聚合，这样会快比较多，也不会显著掉点？

**Comment by CharlesPikachu** [comment]
是的，可以的，但是我没有做过太多这方面的实验，如果有更高效的方式融合历史特征肯定是更好的

**Comment by jyang68sh** [comment]
谢谢反馈。

我将会做一些实验，如果有好的结果我会分享给你。
