### ISSUE TITLE
Training on custom dataset with 4 channels

### ISSUE THREAD

**Issue by cspearl** [SegmentationBLWX/sssegmentation#28]
Hi,
I want to train my own dataset which has images in 4 channels - RGB images and IR(infrared) images. Could you help me out with that? How can i modify the codes of this repo to accommodate that extra channel?

**Comment by CharlesPikachu** [comment]
just adjust the in_channels of the backbone in the config, e.g., https://github.com/SegmentationBLWX/sssegmentation/blob/main/ssseg/configs/annnet/base_cfg.py#L68:

```
'backbone': {
        'type': 'resnet101',
        'series': 'resnet',
        'pretrained': True,
        'outstride': 8,
        'use_stem': True,
        'selected_indices': (2, 3),
       'in_channels': 3,
},
```
in_channels is added in the backbone cfg in SEGMENTOR_CFG

**Comment by cspearl** [comment]
So I will have to add that field since it is not there in any of the configs that I went through?

'in_channels' : 4 

Adding this in the backbone dict.

And how would I take the input of those IR images?

**Comment by CharlesPikachu** [comment]
Yes, 'in_channels' is set as 3 by default during building backbones, so I do not need to set it in backbone dict for my training tasks. As for your task, you can manually specify 'in_channels' by adding the key in the backbone dict. (the code implementation is just similar to backbone.get('in_channels', 3))

And for the second question, I believe you can simply concatenate RGB images and IR images if you have no ideas to deal with it.

**Comment by cspearl** [comment]
Thanks! will try that
