### ISSUE TITLE
医学图像分割也很有意义，我想给你一些公开的医学图像数据集。哈哈哈哈

### ISSUE THREAD

**Issue by S-HuaBomb** [SegmentationBLWX/sssegmentation#3]
Hi @CharlesPikachu ！UNet 也是大名鼎鼎的分割模型啊，它在医学图像分割领域是 SOTA，个人认为 `Supported Models` 列表里应该有名字，而且应该在 FCN 之后。哈哈哈 🥇 

虽然 [PyTorch Hub](https://pytorch.org/hub/mateuszbuda_brain-segmentation-pytorch_unet/) 已经有预训练的 UNet 了，但我想要皮卡丘也有！  🛩️ 

这里提供一些医学数据集给你参考：
- PyTorch Hub 里预训练 UNet 的数据集：[LGG Segmentation Dataset](https://www.kaggle.com/mateuszbuda/lgg-mri-segmentation)
- [DDTI](https://pan.baidu.com/share/init?surl=E-28rkg94Jc8NLyKhe2q3g)，已经按照下一个数据集的格式预处理过，百度网盘提取码：`qxds`
- [tn-scui2020](https://tn-scui2020.grand-challenge.org/Dataset/)，来自比赛 [tn-scui2020](https://tn-scui2020.grand-challenge.org/evaluation/challenge/leaderboard/)
- [百度 AI Studio 医学影像数据集集锦](https://aistudio.baidu.com/aistudio/projectdetail/462184)
- [List of Medical Datasets](https://github.com/adalca/medical-datasets)，来自 GitHub

**Comment by CharlesPikachu** [comment]
Ok, I will add the support of UNet in the recent update
