### ISSUE TITLE
ssseg/modules/models/segmentors/memorynet/initmemory.py

### ISSUE THREAD

**Issue by 60wanjinbing** [SegmentationBLWX/sssegmentation#31]
initmemory.py  请问这个文件的作用是啥？这个文件在训练的时候有不有用到？

**Comment by CharlesPikachu** [comment]
用不到，paper里ablation study的时候用了，所以一起上传了

**Comment by 60wanjinbing** [comment]
During training, we first randomly select one pixel representation for each category from the train set to initialize M。我看代码里面貌似没有这个随机选择初始化M

**Comment by CharlesPikachu** [comment]
update的时候加了判断
