### ISSUE TITLE
关于每个数据集的通道正则化

### ISSUE THREAD

**Issue by NJNUCS** [SegmentationBLWX/sssegmentation#33]
您好，我有点疑惑，请问VOC, Cityscapes , Ade20k数据集的正则化都是：
    ('Normalize', {'mean': [123.675, 116.28, 103.53], 'std': [58.395, 57.12, 57.375]}),  嘛

**Comment by CharlesPikachu** [comment]
是的，这个由pre-train时候的正则化决定，和segmentation的数据集无关

**Comment by NJNUCS** [comment]
谢谢您及时的回复

**Comment by NJNUCS** [comment]
冒昧的再问您一个问题，MCIBI++在使用PSPNet网络在COCOStuff-10k上训练时，优化器中引入了'min_lr': 1e-4,但是FCN和UperNet中却没有这样的设置，请问这个是什么意思呀

**Comment by CharlesPikachu** [comment]
poly算lr时候的min lr，相当于最后一个iteration的lr=1e-4

**Comment by NJNUCS** [comment]
谢谢您的回答，我明白了，我最近在复现您的模型MCIBI++在COCOStuff10k上的结果，我看您用的是V1.1版本的数据集，我发现这个数据集中有182个类，但是有11个类在标签中并没有被标记，我看您的代码中写的类别是182个，然后我训练出来的类的结果这没有被标记的11个类的miou是nan,我想请问您，这样训练会有实验误差嘛

**Comment by CharlesPikachu** [comment]
没有，你可以自己测试一下，nan不参与计算miou

**Comment by NJNUCS** [comment]
好的，谢谢您
