### ISSUE TITLE
关于VSPW数据集训练

### ISSUE THREAD

**Issue by dalexin** [SegmentationBLWX/sssegmentation#37]
作者您好，您在论文中提到在训练VSPW数据集时使用了2帧历史帧以获取时序信息，但是在代码中没有看到相关的模块或结构，vspw数据集的读取代码中使用了random.choice()只能随机读取一帧，请问相关部分的代码能麻烦您帮忙指出或提供吗，万分感谢！

**Comment by CharlesPikachu** [comment]
之前在字节做的，video部分没有备份，这边只有一个draft的code，你可以邮箱给我，我发给你
