### ISSUE TITLE
Do we have any usage examples? 

### ISSUE THREAD

**Issue by shravankumar-concat** [SegmentationBLWX/sssegmentation#38]
- For Custom Datasets
- For Fine-tuning

**Comment by CharlesPikachu** [comment]
Here is a simple document: https://sssegmentation.readthedocs.io/en/latest/

For custom datasets, you can refer to the code in datasets directory: https://github.com/SegmentationBLWX/sssegmentation/tree/main/ssseg/modules/datasets

**Comment by shravankumar147** [comment]
Good place to start here: [ssseg tutorials](https://sssegmentation.readthedocs.io/en/latest/Tutorials.html)
