### ISSUE TITLE
 assert num_classes == len(classnames) and num_classes == len(palette)

### ISSUE THREAD

**Issue by umarjibrilmohd** [SegmentationBLWX/sssegmentation#48]
the previous error has gone when i made the number of classes 2, now left with this.
 File "/home/mohammed/sssegmentation/ssseg/modules/datasets/ade20k.py", line 83, in <module>
    class ADE20kDataset(BaseDataset):
  File "/home/mohammed/sssegmentation/ssseg/modules/datasets/ade20k.py", line 108, in ADE20kDataset
    assert num_classes == len(classnames) and num_classes == len(palette)
AssertionError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1615854) of binary: /home/mohammed/miniconda3/envs/myenv/bin/python
Traceback (most recent call last):

i set the number of classes as 2 which you can see below.
class ADE20kDataset(BaseDataset):
            num_classes = 2
            classnames = ['defect']
            palette = [(255, 0, 255)]
            clsid2label = {0: 0} 

when i set it like this 
 # num_classes = 2
            # classnames = ['defect', 'no_defect']
            # palette = [(255, 0, 255), (0, 255, 0)]
            # clsid2label = {0: 0, 1: 1}
it leads to the previous error were it shows `t >= 0 && t < n_classes` failed.

the below is how my scenecategory looks

NT_label_2 defect
NT_label_1 defect
NF_label_1 defect
NF_label_0 defect
N7_label_1 defect
N7_label_0 defect
N4_label_2 defect
N4_label_1 defect
N4_label_0 defect
N3_label_3 defect
N3_label_2 defect
N3_label_1 defect
N3_label_0 defect
N2_label_2 defect
N2_label_1 defect
N2_label_0 defect
N1_label_3 defect
N1_label_2 defect
N1_label_1 defect
N1_label_0 defect
m9614_label_9 defect
m9614_label_8 defect
M9287_label_6 defect
M9287_label_4 defect
M9287_label_3 defect
M9287_label_1 defect
M7436_label_8 defect
M7436_label_6 defect
M7436_label_2 defect

**Comment by umarjibrilmohd** [comment]
Idx   Ratio   Train   Val    Name
1     1.02     1150    112    defect

this is my object information in txt file

**Comment by umarjibrilmohd** [comment]
because setting the number of classes to 2 and equating the pallet to the number of classes still leads to this /pytorch/aten/src/ATen/native/cuda/NLLLoss2d.cu:95: nll_loss2d_forward_kernel: block: [0,0,0], thread: [63,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "ssseg/train.py", line 261, in <module>
    main()
  File "ssseg/train.py", line 256, in main
    client.start()
  File "ssseg/train.py", line 154, in start
    loss, losses_log_dict = segmentor(images, targets, **forward_kwargs)
and   File "/home/mohammed/sssegmentation/ssseg/modules/models/segmentors/base/base.py", line 52, in customizepredsandlosses
    return self.calculatelosses(predictions=outputs_dict, targets=targets, losses_cfg=losses_cfg, map_preds_to_tgts_dict=map_preds_to_tgts_dict)
  File "/home/mohammed/sssegmentation/ssseg/modules/models/segmentors/base/base.py", line 188, in calculatelosses
    losses_log_dict[loss_key] = loss_value.item()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1211 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f880e66bd62 in /home/mohammed/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1c4d3 (0x7f880e8ce4d3 in /home/mohammed/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x1a2 (0x7f880e8ceee2 in /home/mohammed/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0xa4 (0x7f880e655314 in /home/mohammed/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x29a469 (0x7f886b028469 in /home/mohammed/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0xae0341 (0x7f886b86e341 in /home/mohammed/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: THPVariable_subclass_dealloc(_object*) + 0x292 (0x7f886b86e642 in /home/mohammed/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #7: /home/mohammed/miniconda3/envs/myenv/bin/python() [0x4e0970]
frame #8: /home/mohammed/miniconda3/envs/myenv/bin/python() [0x4f1828]

**Comment by umarjibrilmohd** [comment]
all responses im getting are related to class label.

the below are some.
It seems not only -1 but also class labels larger than n_classes are not allowed as t >= 0 && t < n_classes.

This is an error with your target labels: t >= 0 && t < n_classes. print your labels and make sure that they are positive and smaller than the number of outputs of your last layer. n_classes should be same as the output of the last layer.

can you please advice?

**Comment by CharlesPikachu** [comment]
First check your labels, make sure there are only two classes in your dataset.

Next, make sure the ignore index consistent with yours. In SSSegmentation, the default ignore index is set as 255, you should change labels with -1 as 255

Finally, make sure the num classes you set in the config is the same as your dataset

**Comment by umarjibrilmohd** [comment]
sorry to ask again, be patient with me please, im new in the fireld, and you're really helping.

i prefer to maintain one class as my thermography images has only one class, which of the loss should i consider to fit my one class?

**Comment by CharlesPikachu** [comment]
to my experience, cross entropy loss setting classes as 2 usually obtain similar performance with binary cross entropy loss. So both losses is ok.
