### ISSUE TITLE
how to prepare dataset

### ISSUE THREAD

**Issue by jeannotes** [SegmentationBLWX/sssegmentation#5]

**Comment by CharlesPikachu** [comment]
The supported datasets could be downloaded from:
`URL: https://pan.baidu.com/s/1TZbgxPnY0Als6LoiV80Xrw 
CODE: fn1i `
To train on the custom datasets，you should create your_dataset_name.py in ssseg/modules/datasets/ to parse your own dataset and add this dataset class into ssseg/modules/datasets/builder.py

**Comment by TiankaiHang** [comment]
Will the scripts to preprocess the raw data be released?

Thanks!
