### ISSUE TITLE
[BUG] The error "FileNotFoundError" occurred when executing spec.loader.exec_module(cfg).

### ISSUE THREAD

**Issue by STHxiao** [SegmentationBLWX/sssegmentation#52]
**Environment (使用环境)**
python=3.10.4
**Screenshot (报错截图)**
The directory '.../fcn/fcn_resnest101os8_voc.py' is exist.
![image](https://github.com/SegmentationBLWX/sssegmentation/assets/46336534/c5794449-8802-47df-aaa2-a7a6094f36d2)

**Comment by STHxiao** [comment]
I tried Python=3.8.14 and this problem still persists.

**Comment by CharlesPikachu** [comment]
what's your running command?

**Comment by STHxiao** [comment]
When I run "python setup.py develop", it works. I don't know why? What does the setup.py do? Can you please tell me? Thank you.

**Comment by STHxiao** [comment]
I have access to the relevant information. Thank you very much !
