### ISSUE TITLE
Failed to build installable wheels for some pyproject.toml based projects (chainercv)

### ISSUE THREAD

**Issue by zhushk21** [SegmentationBLWX/sssegmentation#57]
When I installed chainercv, I encountered the following error. 
-----------------------------------------------------------------------------------------------------------------------------------------------------
      chainercv\utils/bbox/_nms_gpu_post.c(194): fatal error C1083: 无法打开包括文件: “longintrepr.h”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chainercv
  Running setup.py clean for chainercv
Failed to build chainercv
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (chainercv)`

**Comment by CharlesPikachu** [comment]
One simple solution is to modify requirements.txt to delete chainercv. Evaluation class will be used to evaluate model performance
