### ISSUE TITLE
[Question] There are some less convenient settings in transforms.py

### ISSUE THREAD

**Issue by STHxiao** [SegmentationBLWX/sssegmentation#61]
1.In RandomFlip, RandomRotation, RandomGaussianBlur, and PILRandomGaussianBlur, augmentation is not performed when prob is set to 1, which seems to go against the intuition that the higher the prob, the higher the probability of occurrence. Should the judgment statement be changed to `if np.random.rand() > self.prob: return sample_meta`
2.In RandomCutOut `sample_meta[key][y1: y2, x1: x2, :] = fill_value` doesn't apply to the `seg_target `output from Resize class because it has a shape of `(h,w)` rather than `(h,w,1)`

**Comment by CharlesPikachu** [comment]
thanks for your suggestions, bugs are fixed in tle latest commit
