### ISSUE TITLE
[Question] ResNet50 layer3 doesn't change the size to half of the original

### ISSUE THREAD

**Issue by STHxiao** [SegmentationBLWX/sssegmentation#62]
Is this correct? The feature map in the paper seems to change to half of what it was after layer3.

Paper structure:
![image](https://github.com/user-attachments/assets/45dd6af7-c9ed-45ae-b603-522c63099cb3)

Layer3 structure:
![image](https://github.com/user-attachments/assets/3e4f55d2-bb61-4847-a76f-657fce262cf3)

**Comment by CharlesPikachu** [comment]
for segmentation tasks, decrease stride and increase dilation to keep receptive field fixed while enlarge output size is a common trick to boost segmentation performance. You can refer to previous segmentation papers and other codebases to check it.

**Comment by STHxiao** [comment]
Thanks for the explanation！
