### ISSUE TITLE
[qus]What psamask do in PSANet?

### ISSUE THREAD

**Issue by STHxiao** [SegmentationBLWX/sssegmentation#63]
What is the role of psamask and how should the dimensions of the mask be determined, the relevant papers don't seem to explain it clearly, can you provide some answers or references? Thanks!

**Comment by CharlesPikachu** [comment]
you can refer the official repo: https://github.com/hszhao/semseg/blob/7192f922b99468969cfd4535e3e35a838994b115/model/psanet.py#L101

**Comment by STHxiao** [comment]
Thanks very much!
