### ISSUE TITLE
[BUG] celoss not support pointrend points input

### ISSUE THREAD

**Issue by STHxiao** [SegmentationBLWX/sssegmentation#64]
The point input x_src shape is (N,C,D), x_tgt shape is (N,D). The assert is `assert (x_src.dim() == 4 and x_tgt.dim() == 3) or (x_src.dim() == 2 and x_tgt.dim() == 1) or (x_src.size() == x_tgt.size())`

**Comment by CharlesPikachu** [comment]
it seems the latest version does not have this issue.
