### ISSUE TITLE
Hi, how many gpus did you use?

### ISSUE THREAD

**Issue by TiankaiHang** [SegmentationBLWX/sssegmentation#8]
For example, PSPNet resnet50, cityscapes 1024 * 512

**Comment by CharlesPikachu** [comment]
By default, I use four Tesla-V100-32GB GPUs for training the models.

**Comment by TiankaiHang** [comment]
Got that, thanks~

------------------
for this setting, [For example, PSPNet resnet50, cityscapes 1024 * 512], if you set bs =16, will it run out of memory?

**Comment by CharlesPikachu** [comment]
I have not met this situation during training. If your GPU memory is limited, you can try to set output stride as 16 and use more GPUs since we use syncbn by default.

**Comment by CharlesPikachu** [comment]
I have not met this situation during training. If your GPU memory is limited, you can try to set output stride as 16 and use more GPUs since we use syncbn by default.

**Comment by TiankaiHang** [comment]
I used two 2080Ti (11G) GPU to train models.

While i set 'img_per_gpu = 1' , it need 3~4GB memory per gpu, however, when i try to double the 'batchsize', it ran out of the memory.

My setting:
'PSPNet resnet50 os16, cityscapes 1024 * 512'

**Comment by CharlesPikachu** [comment]
1. Our framework only supports setting  `batch_size`  rather than `img_per_gpu`, so img_per_gpu = batchsize / num_gpus.
2. I think 11GB * 2 is enough for `PSPNet resnet50 os16, cityscapes 1024 * 512, batchsize=4` since resnet50os8 only requires  6.9 GB per GPU.

**Comment by CharlesPikachu** [comment]
Hello, for `PSPNet resnet50 os16, cityscapes 1024 * 512, batch_size=4`，it requires 11374MiB GPU memory per GPU if you only own two GPUs.

**Comment by TiankaiHang** [comment]
Thanks for your kind answer!
